### ISSUE TITLE
Continued Development

### ISSUE THREAD

**Issue by creativeworkssystems** [agapiospanos/cyberpanel-borg#1]
Just wondering if there will be any continued development of this tool?
I'm finding it super useful to manage multiple servers

**Comment by agapiospanos** [comment]
Hi. Thanks for your interest in this project. At the moment I don't foresee any future development on this project. The reason is that I gave up on Cyberpanel for something else as I was having some issues with lightspeed that couldn't be fixed. Now that I don't actively use this panel I don't have a personal interest any more to continue the dev on that. Hopefully there won't be any breaking changes on the Cyberpanel's side (e.g. database or file structure changes) and the backup scripts will continue to work.

**Comment by creativeworkssystems** [comment]
I see, thank you for the project, it's a great help.
